調整靜態資源調用路徑
nk2028/qieyun-tools pull request #8
Opened 2022-06-09 05:37 UTC by Jiew-KueJwiaeng

2022-08-02 07:15 UTC, syimyuzya requested changes

2022-08-02 07:15 UTC, syimyuzya commented on index.html
> +<html lang="zh-cmn-Hant-HK">
`zh-HK` 是妥當的。

首先，本頁面語言並不是 `cmn`，而是現代書面語（這部分也可以算 `cmn`）與古漢語文本的混合，而且 `cmn` 標籤屬於 extlang，一般只有存在對立時才需要指定，因此語言標籤用 `zh` 即可。（順帶一提，即使真的是要用 `cmn` 的場合，也最好依 IETF 的推荐，單寫 `cmn` 而非 `zh-cmn`）

其次，IETF 並不推荐把蘊含的標籤缺省值全寫出來（比如 `en` 不需要寫成 `en-Latn`，而像 `en-Shaw` 之類的才需要寫出來），而 `zh-HK` 是蘊含了 `Hant` 的。

2022-08-02 09:27 UTC, ayaka14732 commented on index.html
> +<html lang="zh-cmn-Hant-HK">
我的文章：https://ayaka.shn.hk/langtag/

2023-03-13 06:30 UTC, closed without merging

2023-03-13 06:33 UTC, graphemecluster commented
刪 branch 自動 close 掉了